version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    user: root
    stdin_open: true
    tty: true
    init: true
    working_dir: /app
    environment:
      PORT: 8101
    ports:
      - 8101:8101
    volumes:
      - ./:/app:cached
